<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mainBanner_plp</name>
   <tag></tag>
   <elementGuidId>197c6085-3e3a-4296-872a-6b5ca0bd4680</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//img[@id='mainBanner'])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.o-blp-mainContent.order-1.order-lg-2.px-0.px-lg-0.d-none.d-lg-block > div.contaier-fluid.p-0 > div.row > div.container-promo01.col-12.col-lg-12 > a.m-mainBanner__link > picture.img-zoom > #mainBanner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c9e2ed4a-2a4e-4ad9-8c31-176a40d32492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainBanner</value>
      <webElementGuid>68622a4a-ac4c-4ff0-ac73-1870b711ab59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-mainBanner__image lazyloaded</value>
      <webElementGuid>06480f44-93c8-4628-b01c-759970b68268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://assetspwa.liverpool.com.mx/assets/digital/landing/mujer/blp_vestidos_121222.jpg</value>
      <webElementGuid>8f7a1cb3-4bcc-4de6-ba39-3bacfe4aced7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Renta de vestidos | Liverpool</value>
      <webElementGuid>1e15f2da-40f7-4608-899b-654d32eec4d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Renta de vestidos | Liverpool</value>
      <webElementGuid>2cfec7f4-f155-4e8d-8d76-f06cb2600fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assetspwa.liverpool.com.mx/assets/digital/landing/mujer/blp_vestidos_121222.jpg</value>
      <webElementGuid>191561f3-ca7a-41ed-a111-aabe93af4128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/div[1]/div[@class=&quot;container-fluid o-main-container p-0 o-blp-secondaryContainer&quot;]/div[@class=&quot;container o-container__secondary&quot;]/div[@class=&quot;row mt-lg-3 m-row-bootstrap&quot;]/main[@class=&quot;col-lg-9 m-column_mainContent&quot;]/div[@class=&quot;o-blp-mainContent order-1 order-lg-2 px-0 px-lg-0 d-none d-lg-block&quot;]/div[@class=&quot;contaier-fluid p-0&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;container-promo01 col-12 col-lg-12&quot;]/a[@class=&quot;m-mainBanner__link&quot;]/picture[@class=&quot;img-zoom&quot;]/img[@id=&quot;mainBanner&quot;]</value>
      <webElementGuid>55f8d575-9a2b-4c58-bfba-b9869c9761c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//img[@id='mainBanner'])[10]</value>
      <webElementGuid>992bab67-ceee-4b19-8151-f6fa0d16ef97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div[4]/main/div[2]/div/div[4]/div/a/picture/img</value>
      <webElementGuid>38ccf594-9993-4954-8bfa-7f15433c34ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Renta de vestidos | Liverpool'])[2]</value>
      <webElementGuid>30c9dc76-071b-4e11-9bd8-4c3e44ca0da6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/div/a/picture/img</value>
      <webElementGuid>35e47566-5439-479a-a38d-92fd438d627a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'mainBanner' and @alt = 'Renta de vestidos | Liverpool' and @title = 'Renta de vestidos | Liverpool' and @src = 'https://assetspwa.liverpool.com.mx/assets/digital/landing/mujer/blp_vestidos_121222.jpg']</value>
      <webElementGuid>4ee607d0-dd8f-41ff-aba2-6649476a7f0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
