<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify_Img_1_plp</name>
   <tag></tag>
   <elementGuidId>331eb25d-365f-4fa0-b7bf-d348d418eb25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='img_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#img_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5abb87e6-4183-4a97-835c-40edff2ea6d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>aebdab08-d938-4fa7-9a63-63781cd9e9be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ss701.liverpool.com.mx/lg/1011422132.jpg</value>
      <webElementGuid>0dbe1320-d892-43fa-ab03-e8c5c2e110fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Lipstick M.A.C Retro Matte</value>
      <webElementGuid>3317c2c0-91dc-4786-868c-3041f045c702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img_1</value>
      <webElementGuid>2f1054a8-efea-4e19-92e3-a2580b890ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img_1&quot;)</value>
      <webElementGuid>e8270809-ebf7-4daf-a8c0-29c9c7ebee84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='img_1']</value>
      <webElementGuid>418e7d36-1a9d-43ce-8905-2b6328415acb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[4]/main/div[2]/div/div/ul/li[2]/a/div/figure/div/section/img</value>
      <webElementGuid>ab0df6eb-eec8-4afd-aa77-9cbc5d9aa96e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Lipstick M.A.C Retro Matte']</value>
      <webElementGuid>030ca252-724d-4afa-b0ae-9ccfadd8edf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/div/figure/div/section/img</value>
      <webElementGuid>b6430f69-0066-4bf7-b269-92f792a268c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ss701.liverpool.com.mx/lg/1011422132.jpg' and @alt = 'Lipstick M.A.C Retro Matte' and @id = 'img_1']</value>
      <webElementGuid>ce3e5b37-a5ad-484c-a192-37046ecf547e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
