<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>shortName_addAddress_opc (1)</name>
   <tag></tag>
   <elementGuidId>5817a507-7160-4885-bf1e-d4500496fc5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='shortName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;shortName&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>25c333c1-8473-47c5-8fa1-f1c927dbcda7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-textField__input mdc-text-field__input</value>
      <webElementGuid>670442f9-e5e7-4a64-a170-c19541c2c158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0413f520-30d3-4169-ac39-3641e7c29ecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>795882fd-3d52-4be6-94a8-6c0e44cface1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>helper-nombreCorto</value>
      <webElementGuid>69113f78-ef09-4d01-8119-464938ac9ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>helper-nombreCorto</value>
      <webElementGuid>55d3b64a-dee3-49cc-828b-7ee9f33a04cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shortName</value>
      <webElementGuid>cf51d5ba-58aa-4482-b6a6-f8f10501ea6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d7c0f907-08e7-430a-9b7c-8b30bd4b47e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationtype</name>
      <type>Main</type>
      <value>onlyMaxLength</value>
      <webElementGuid>a6011079-071e-4d10-b812-1826e481fa2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>53ab51e2-742a-459b-b622-66358fefe986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>reference</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>3d420d83-1220-4046-802e-ad38bbbaee7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputid</name>
      <type>Main</type>
      <value>nombreCorto</value>
      <webElementGuid>56aca1ca-16c9-4e09-b7e4-53c145a554b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nameinput</name>
      <type>Main</type>
      <value>nombreCorto</value>
      <webElementGuid>29cb3310-e18d-408d-a800-3e72c211b379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>labeltext</name>
      <type>Main</type>
      <value>Alias de la dirección:</value>
      <webElementGuid>c9098409-ab1e-4617-8b1f-e0d9375fb6f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>labelposition</name>
      <type>Main</type>
      <value>left</value>
      <webElementGuid>c5fd803b-e057-46fe-ad66-765e09012ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>helpertextid</name>
      <type>Main</type>
      <value>helper-nombreCorto</value>
      <webElementGuid>37cfb198-1c8f-4813-a04b-d040023478a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opc_modalAddNewShipAddress&quot;)/form[1]/div[@class=&quot;row align-items-start&quot;]/div[@class=&quot;col-xl-3 col-lg-3 col-12 alias-direction&quot;]/div[@class=&quot;m-textField mdc-text-field mdc-text-field--outlined mdc-text-field--focused mdc-text-field--valid&quot;]/input[@class=&quot;a-textField__input mdc-text-field__input&quot;]</value>
      <webElementGuid>847c3bb3-ec4f-4dea-9fab-c851b6c2facf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='shortName']</value>
      <webElementGuid>bc582703-ebf1-4f9b-bc82-facb2d96e6e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='opc_modalAddNewShipAddress']/form/div[4]/div/div/input</value>
      <webElementGuid>93eae5a0-da13-4659-afb7-1539a1088606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>9ef42e65-ed52-49ea-aa11-7b4343547f40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'shortName' and (text() = 'text' or . = 'text')]</value>
      <webElementGuid>d380bc9d-fc5f-4317-8813-584a75187899</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
